{
 "title": "[1] Overview",
 "tags": [
  "promscale",
  "apm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Services (Last 30 minutes)",
   "type": "table",
   "gridPos": { "h": 24, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    service_name AS \"Service\",\n    COUNT(*)::numeric / (30 * 60) AS \"Requests\",\n    AVG(duration_ms) AS \"Avg Duration\",\n    ROUND(approx_percentile(0.90, percentile_agg(duration_ms))::numeric, 3) AS \"p90 Duration\",\n    (count(*) filter (where status_code = 'error')::numeric / count(*)) AS \"Error rate\"\nFROM ps_trace.span s\nWHERE start_time > NOW() - INTERVAL '30m'\nAND (span_kind = 'server' OR parent_span_id is NULL)\nGROUP BY 1\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Slowest Requests (last 30 minutes)",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  replace(trace_id::text, '-'::text, ''::text) as \"Trace ID\",\n  service_name as \"Service\",\n  span_name as \"Operation\",\n  start_time as \"Time\",\n  duration_ms as \"Duration\" \nFROM ps_trace.span\nWHERE start_time > NOW() - INTERVAL '30m'\nAND parent_span_id is null\nORDER BY duration_ms DESC\nLIMIT 50\n;"
    }
   ]
  },
  {
   "title": "Most Common Errors (last 30 minutes)",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  status_message as \"Error\",\n  service_name as \"Service\",\n  count(*) as \"Occurrences\" \nFROM ps_trace.span\nWHERE start_time > NOW() - INTERVAL '30m'\nAND status_code = 'error'\nGROUP BY 1, 2\nORDER BY 3 DESC\n;"
    }
   ]
  }
 ]
}