{{- if .Values.maintenance.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "promscale.fullname" . | trunc 51 }}-maintenance
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.maintenance.schedule }}
  startingDeadlineSeconds: {{ .Values.maintenance.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.maintenance.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.maintenance.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-maintenance
            image: postgres:12-alpine
            {{ if .Values.maintenance.resources }}
            resources:
              {{ toYaml .Values.maintenance.resources | nindent 14 }}
            {{ end }}
            args:
            - sh
            - ./execute_maintenance.sh
            env:
              {{- if not .Values.connection.uri.secretTemplate }}
              - name: PGPORT
                value: {{ .Values.connection.port | quote }}
              - name: PGUSER
                value: {{ .Values.connection.user }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.password.secretTemplate . }}
                    key: {{ .Values.connection.password.timescaleDBSuperUserKey }}
              - name: PGHOST
                value: {{ tpl .Values.connection.host.nameTemplate . }}
              - name:  PGDATABASE
                value: {{ .Values.connection.dbName }}
              {{- else }}
              - name: PROMSCALE_DB_URI
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.connection.uri.secretTemplate . }}
                    key: {{ .Values.connection.uri.key }}
              {{- end }}
            volumeMounts:
              - name: script-volume
                mountPath: /execute_maintenance.sh
                subPath: execute_maintenance.sh
          volumes:
            - name: script-volume
              configMap:
                name: {{ include "promscal.fullname" . | trunc 51 }}-maintenance
          restartPolicy: OnFailure
          {{- with .Values.maintenance.nodeSelector }}
          nodeSelector:
          {{ toYaml . | indent 2 }}
          {{- end }}
          {{- with .Values.maintenance.tolerations }}
          tolerations: {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.maintenance.affinity }}
          affinity: {{ toYaml . | nindent 12 }}
          {{- end }}
{{- end -}}