name: goreleaser

on:
  push:
    branches: [master, main, force_test, release-*, staging, trying]
    tags: ['*']
  pull_request:
    branches: ['**']

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.16
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        #login only on tags. Note that login can't work on PRs from forked repos because of missing secrets
        #this gets around that by only logging in when needed.
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Run GoReleaser Test
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --skip-publish --rm-dist -f build/.goreleaser.yml
      -
        name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        #release only on tags
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f build/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}